name: flutter_practice_mvvm
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Routing
  auto_route: ^10.0.1

  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0

  # Misc
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  easy_localization: ^3.0.7+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flavor
  flutter_flavorizr: ^2.4.0

  # Analysis
  pedantic_mono: ^1.30.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  dart_code_metrics_presets: ^2.22.0

  # Build Runner
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0
  auto_route_generator: ^10.0.1
  flutter_gen_runner: ^5.10.0
  easy_localization_sheet: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/images/news/

flutter_gen:
  output: lib/gen

  assets:
    exclude:
      - assets/translations/*

easy_localization_sheet:
  csv_url: "https://docs.google.com/spreadsheets/d/16EW--sPe2Gg-O77_rPaY8BFV35sft-pA5t6dlPIaU4Q/export?format=csv"
  output_dir: "assets/translations"
  easy_localization_generate:
    output_dir: lib/gen
    output_file_name: locale_keys.g.dart
